wa_task_management_api:
  url: ${WA_TASK_MANAGEMENT_URL:http://localhost:8087}

core_case_data:
  api:
    url: ${CCD_URL:http://ccd-data-store-api}

azure:
  servicebus:
    connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
    topic: ${AZURE_SERVICE_BUS_TOPIC_NAME:ccd-case-events-aat}

govUk:
  url: https://www.gov.uk/
